# http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
# http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
env:
  - SHAARLI_SRC=https://github.com/sebsauvage/Shaarli/archive/master.tar.gz
  - SHAARLI_SRC=https://github.com/shaarli/Shaarli/archive/master.tar.gz
  - SHAARLI_SRC=https://github.com/shaarli/Shaarli/archive/v0.0.40beta.tar.gz
  - SHAARLI_SRC=https://github.com/shaarli/Shaarli/archive/v0.5.3.tar.gz
install:
  - ./scripts/install.sh
# https://github.com/shaarli/Shaarli/issues/16#issuecomment-136669639
# http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
# http://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps
script:
  - ./scripts/run-tests.sh
